[build]
  command = "# no build command"
  publish = "."
  functions = "functions"

[dev]
  framework = "php"
  command = "php -S localhost:8888"
  port = 8888
  targetPort = 8888
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
  force = false
  conditions = {Path = {match = "\\.[css|js|jpg|png|gif|svg|webp]$", ignore = ""}}

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions."*"]
  included_files = ["**/*.php"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' cdnjs.cloudflare.com; img-src 'self' images.unsplash.com data:; font-src 'self' cdnjs.cloudflare.com;"
